name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: cargo build --verbose

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: cargo test --release --verbose

    clippy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: cargo clippy

    build-benchmarks:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: cargo build --benches

    doc:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: cargo doc
